### ISSUE TITLE
UnionNullMapArrayString/MapArrayString keys and values left un-initialized by deserializer

### ISSUE THREAD

**Issue by homiak** [actgardner/gogen-avro#100]
Deserialize does not appear to be using the NewMapArrayString constructor 

```
func NewMapArrayString() *MapArrayString {
	return &MapArrayString{
		keys:   make([]string, 0),
		values: make([][]string, 0),
		M:      make(map[string][]string),
	}
}
```

(which initializes keys and values to empty arrays)
when deserializing the values. This leads to the difference between serialized and deserialized values. This is hugely annoying in tests, when you cannot use reflect.deepEquals() because keys and values would be nil vs empty array.

**Comment by zimbabao** [comment]
After populating Map call `Finalize()` on map and then serialize the map. 
IIUC That should solve the problem.

**Comment by homiak** [comment]
Thanks for the suggestion @zimbabao!

**Comment by actgardner** [comment]
I know the API around maps is clumsy at the moment, I'd like to eliminate the intermediate struct type altogether so these are just regular maps (instead of structs wrapping a map). In the meantime I think this is working as intended, even if it isn't the best experience. Thanks for documenting this for future users!
