### ISSUE TITLE
Performance problem deserializing messages

### ISSUE THREAD

**Issue by mrjackbo** [actgardner/gogen-avro#139]
My use case is as follows: I am reading avro messages from kafka. I know that they are all serialized using a particular schema. For this schema, let's call it `DemoSchema`, I have generated code using gogen-avro. I deserialize the messages using 
```
avro.DeserializeDemoSchema(bytes.NewReader(message.Value))
```
I noticed unexpectedly high CPU usage, and the cause appears to be [here](https://github.com/actgardner/gogen-avro/blob/6fdda8d67932d841f82ae52b7f07a5d9199bf6cb/v7/example/avro/demo_schema.go#L35). For each deserialization, gogen-avro parses the avro schema json...twice. 
Once I use `vm.Eval` directly, the CPU usage drops and the read throughput increases dramatically. 

I noticed that in the container methods, you provide a `DemoSchemaReader` which only parses the schemas on creation. But the container methods do not quite fit this use case. Do you have any suggestions, or can you provide a deserialization method which skips schema verification, for situations in which one knows the schema of the data?

**Comment by actgardner** [comment]
Hey @mrjackbo! 

> Once I use vm.Eval directly, the CPU usage drops and the read throughput increases dramatically.

`DeserializeDemoSchema` is basically a convenience method for the simple case where the reader and writer schemas are identical and performance isn't crucial. To maximize throughout I recommend exactly what you describe: compile the bytecode for your schema once, and then `vm.Eval` repeatedly. `vm.Eval` can even be fanned out to multiple goroutines to deserialize multiple records in parallel.

It's worth noting `CompileSchemaBytes` does multiple things: it deserializes and validates the JSON, but it also generates the bytecode program which the VM runs. This program is unique for each pair of reader and writer schemas, which is why the API is slightly more complicated.

**Comment by mrjackbo** [comment]
Thanks @actgarnder, I'll do it like this then.
