### ISSUE TITLE
Read OFC files?

### ISSUE THREAD

**Issue by boompig** [actgardner/gogen-avro#41]
Hi, I'm new to Golang, so feel free to close if this is very obvious.

What's the canonical way to read multiple records from an OFC container file using this repo? If performing a naive read, you get an error (presumably because you're trying to read records where the OFC headers are).

**Comment by JensRantil** [comment]
If it was supported, there would have been coded in https://github.com/actgardner/gogen-avro/tree/master/container for reading containers. I can't find any such support.

**Comment by actgardner** [comment]
HI, sorry for the slow reply! We don't currently have support for reading Object Container Files but it would be simple to implement. If you give me a few days I should be able to implement this.

Note that we don't support schema evolution right now, so this support would require that you provide a struct whose schema matches the schema of the OCF.

**Comment by actgardner** [comment]
Hey @boompig, I know this issue is pretty stale but I finally found the time to add some experimental OCF reading support. You can create a `container.Reader` that wraps your `io.Reader` and unpacks the container format. You should be able to just pass the `container.Reader` to the generated deserializer and it will work _as long as the writer schema is exactly the same as the reader schema_. Evolution still isn't supported, and right now this will just blindly deserialize whatever it gets which might panic or return incomplete or corrupt records if the schemas aren't the same.

For an example see: https://github.com/actgardner/gogen-avro/blob/master/test/primitive/container_test.go#L99

**Comment by actgardner** [comment]
@boompig If you're still interested, I have a new branch which is a beta for v6.0. It includes simpler OCF file reading and schema evolution: https://github.com/actgardner/gogen-avro/tree/gadgt

I'm going to close this issue, if you have any problems with the branch feel free to open a new issue!
