### ISSUE TITLE
Add support for JSON tags on the generated structs automatically

### ISSUE THREAD

**Issue by maarek** [actgardner/gogen-avro#79]
Provide support for generating struct tags for json parsing according to the AvroSchema Sepcification. 

Use case: Marshaling Avro Schemas to Json responses from Rest API. Useful when publishing Avro records to Confluent Rest Proxy which takes an Avro Schema + Json Records.

Example of a Json tagged struct:
```
type User struct {
  Id        int       `json:"id"`
  Name      string    `json:"name"`
  Bio       string    `json:"about,omitempty"`
  Active    bool      `json:"active"`
  Admin     bool      `json:"-"`
  CreatedAt time.Time `json:"created_at"`
}
```

By default json:name should be the original name defined in the schema. 

Optional:
Ability to ignore a field `json:"-"` 
Ability to omit empty (not sure on use within tools like Confluent Rest Proxy, if it expects explicit null definitions or not)

**Comment by maarek** [comment]
#76 #77

**Comment by jeroenrinzema** [comment]
I would like to propose a couple of new properties to support the golang json tag functionalities:

```json
{
  "golang.json.omitempty": true,
  "golang.json.ignore": true,
  "golang.json.name": "alternative_name"
}
```

**Comment by maarek** [comment]
This sounds reasonable to me. 👍

**Comment by maarek** [comment]
@jeroenrinzema When I was playing with Avro IDL today, I noticed that the dot notation is not accepted in the IDL. I am not using extra tags currently but we do do a lot of avdl -> avsc conversions that would fail with the dot notation over underscore  or camel case.

**Comment by jeroenrinzema** [comment]
@maarek thanks for reporting. As far as I can see do we have the following options remaining for the property names:

```json
{
  "golangJsonOmitempty": true,
  "golang-json-ignore": true,
  "golang_json_name": "alternative_name",
  "GolangJsonAlternative": "option"
}
```

I like to use underscores but would like to know what others think.

**Comment by codeyrk** [comment]
I would like to propose the addition of MarshalJSON([]byte, error) wherever applicable which will use the above requested JSON field names from the schema.
I found Enumerations are returned as numbers instead of their string representations.

**Comment by maarek** [comment]
@codeyrk Sorry I am not sure I understand the impacts of this. Are you saying to to provide a means to marshal so that enumerations can be custom transformed to their string representation? My only worry would be tightly coupling the generated code to one single json library. Is there any other way to provide handling of these cases like enumerations?

**Comment by maarek** [comment]
@jeroenrinzema Hyphens are not allowed either so I'd say move back to underscore or camel case. I'll leave it up to you. My standard convention is something like @semVer but I don't want to get stuck bikeshedding on this, just make sure we're in spec. 👍

**Comment by codeyrk** [comment]
@maarek Maybe I am not able to understand your concern. Let me reframe the proposal:
- Configurable support to add MarshalJSON([]byte, error) during code generation. MarshalJSON is called by the standard library "encoding/json" on all the fields, as per [Marshal documentation](https://golang.org/pkg/encoding/json/#Marshal).
Many other libraries are calling this function internally to convert native struct to JSON. Also, as this is a standard library function, even though tightly coupled, would enhance the usability significantly.
- Enumerations which are currently returned as numbers instead of string representations can be resolved by above approach. Existing String function generated for all enumerations could be utilized for string representations. Example generated code:
`
type ESomeType int32
const (
    ESomeTypeA ESomeType = 0
    ESomeTypeB ESomeType = 1
)

func (e ESomeType) String() string {
    switch e {
    case ESomeTypeA:
        return "A"
    case ESomeTypeB:
        return "B"
    }
    return "unknown"
}

func (e ESomeType) MarshalJSON() ([]byte, error) {
    switch e {
    case ESomeTypeA:
        return []byte("\"A\""), nil
    case ESomeTypeB:
        return []byte("\"B\""), nil
    }
    return []byte("unknown"), nil
}
`

**Comment by jeroenrinzema** [comment]
I think it would be worth it exploring the plausibilities including a `MarshalJSON` method to  enumerations.

**Comment by jeroenrinzema** [comment]
@codeyrk could you please open a separate issue for this topic? We could discuss it further over there.

**Comment by actgardner** [comment]
To me the approach in #82 of fulfilling the `Marshaller` interface _seems_ preferable because of support for enumerations, but also for unions. I think trying to drive JSON serialization using tags is going to result in a lot of edge cases leaking gogen-avro-specific hacks into the structure of the JSON, which will make it hard to line up with how other languages handle JSON-Avro mappings.

**Comment by jeroenrinzema** [comment]
I think we could postpone the release of automatic JSON tags generation until we have covered all/most of the edge cases. I also think that it would be best to refactor parts of this package before implementing full JSON support. I will open a PR once you have released `v6`.

**Comment by actgardner** [comment]
This should be resolved on master now, it'll go into the next major release (7.0):

- unions encode as null or a map of `{"type": "value"}`
- enumerations encode to their names 
- record structs include JSON tags to use the Avro field names instead of the generated Golang field names

To my knowledge this should bring us in line with the spec and other Avro implementations. If anyone has the bandwidth to try it out and report any bugs or inconsistencies I'd really appreciate it.
