### ISSUE TITLE
Replace gopkg.in and dep with Go Modules

### ISSUE THREAD

**Issue by y0ssar1an** [actgardner/gogen-avro#80]
`gopkg.in` is the old way of locking versions of packages, in the Dark Ages before we had proper dependency management in Go. Even using just `dep` would be an improvement over `gopkg.in`.
Hosting the project under two domains -- `gopkg.in` and `github.com`  -- adds unnecessary confusion and complexity to anybody trying to use `gogen-avro`. I ran into this while trying to use `gogen-avro` using modules. I found that I could not stop `go` from fetching from _both_ URLs. I have references in my `go.mod` file to both URLs, and the generated code is using `gopkg.in` for imports.
```
"gopkg.in/actgardner/gogen-avro.v5/container"
```
This is not what I want. I want to import the `github.com` URLs, not the obsolete old URLs.

The best solution would be to migrate to using modules, which are the new standard for Go dependency management. If you don't like modules for some reason, please pick one method of dependency management -- `gopkg.in` or `dep` -- so we can avoid these headaches. Thanks!

Update: When I say _headaches_, I mean this is breaking my builds and I'm struggling to understand why.
```
.generated/avro/gulp_metadata.go:27:2: no Go files in /go/src/github.com/foo/bar/vendor/gopkg.in/actgardner/gogen-avro.v5/container
```

**Comment by actgardner** [comment]
This project has been around for a few years, and it's gone through a few iterations of package management and versioning to try and meet user's needs. Since I'm the only maintainer, I don't always have bandwidth to adopt the latest-and-greatest language features. The current system with gopkg.in is definitely cumbersome, and the value it provided to help users version their toolchains (and not just the code they import) has largely been superceded by dep and retool.

I'm planning on releasing v6.0.0 soon, which will have a number of substantial breaking changes. This seems like a fine time to move to the new module system and deprecate gopkg.in. I don't have a ton of experience with modules or how the user experience would work for people managing their toolchain (running gogen-avro to generate structs) as well as importing the library for container support (and the new VM).

> This is not what I want. I want to import the github.com URLs, not the obsolete old URLs.

Cool. Can you describe what you _do_ want in more detail? You can import the github URLs today and ignore gopkg.in and I'm pretty sure everything will work - the references to gopkg.in should be on the version branches. If there's references to gopkg.in on master that's a bug. 

I would love to see a PR to add module support, and I would work with you to bring that into the next release.

**Comment by tormoder** [comment]
I'm not using `container` , but I'm locking the version of the generator in my project by using the technique described here: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module.

If I remember correctly, I had to use a "pseudo version" (https://tip.golang.org/cmd/go/#hdr-Pseudo_versions), i.e. a specific commit, to avoid `gopkg.in` imports.

`go get github.com/actgardner/gogen-avro/gogen-avro@46a34be9db23`
is listed as
`github.com/actgardner/gogen-avro v5.1.1-0.20190319215101-46a34be9db23+incompatible`
in my `go.mod` file.

**Comment by y0ssar1an** [comment]
I have a lot of experience with converting projects over to modules, so I'm happy to submit a PR. I've already got a working fork. However, I found that to truly stamp out `gopkg.in`, [I first need to remove it from `linkedin/goavro`](https://github.com/linkedin/goavro/pull/154). If that PR is accepted, I'll update my fork and submit the PR.

**Comment by actgardner** [comment]
Is there a particular reason we need to convert goavro, which is only a dependency for our integration tests, in order to adopt modules in this repo?

**Comment by wfscheper** [comment]
@actgardner, I filed this issue linkedin/goavro#149 that describes the go modules issues with goavro. Bottom line, the v2 gopkg.in import path for goavro is broken for go modules.

**Comment by actgardner** [comment]
The v7 release now uses Go modules! Let me know if there's any issues.
